name: Run Executor linter and tests

on: workflow_dispatch

env:
  PYTHON_DEFAULT_VERSION: "3.11"

jobs:
  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./executor
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox 'pdm>=2.12,<3'
      - name: Run linters
        run: nox -vs lint
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./executor
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox 'pdm>=2.12,<3'
      - name: Setup common virtualenv
        # In order not to exhaust disk on GitHub runner, we use one single
        # virtualenv for all pdm projects: miner, executor, validator.
        run: |
          pdm config venv.backend venv
          python -m venv .venv
          echo "$.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=${{ github.workspace }}/.venv" >> $GITHUB_ENV
          echo "PDM_IGNORE_SAVED_PYTHON=1" >> $GITHUB_ENV
      - name: Prepare environment
        run: ./setup-dev.sh
      - name: Build kkowalskireef/compute-horde-job-echo:v0-latest image
        run: docker build . -t kkowalskireef/compute-horde-job-echo:v0-latest
        working-directory: ./executor/app/src/compute_horde_executor/executor/tests/integration/docker_image_for_tests
      - name: Run unit tests
        run: pdm run nox -vs test --no-venv
