name: "CD: executor (staging)"

on:
  workflow_dispatch:
  push:
    branches:
      - 'deploy-executor-staging'

env:
  BUILD_DIRECTORY: "executor"
  TAG_VERSION: "v0-latest"
  DOCKER_REPO_NAME: "kkowalskireef/compute-horde-executor-staging-tryagain"
  DIST_VERSION_PREFIX: "executor-staging"
  DOCKER_CONTENT_TRUST: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up DCT delegated key
        run: |
          DELEGATION_KEY_FILE="$HOME/.docker/trust/private/${{ secrets.DOCKERHUB_DELEGATED_KEY_ID }}.key"
          mkdir -p $(dirname "$DELEGATION_KEY_FILE")
          touch "$DELEGATION_KEY_FILE"
          chmod 600 "$DELEGATION_KEY_FILE"
          echo "${{ secrets.DOCKERHUB_DELEGATED_KEY }}" > "$DELEGATION_KEY_FILE"

      - name: Docker build and push
        run: |
          IMAGE_NAME="${DOCKER_REPO_NAME}:${TAG_VERSION}"
          SHA_IMAGE_NAME="${DOCKER_REPO_NAME}:git-${GITHUB_SHA}"

          cd "${BUILD_DIRECTORY}" && docker build --build-context compute-horde=../compute_horde -t "${IMAGE_NAME}" -f app/envs/prod/Dockerfile .

          docker image tag "${IMAGE_NAME}" "${SHA_IMAGE_NAME}"

          echo "${{ secrets.DOCKERHUB_KEY }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          echo "${{ secrets.DOCKERHUB_DELEGATED_KEY_PASS }}" | docker sign "${IMAGE_NAME}"
          echo "${{ secrets.DOCKERHUB_DELEGATED_KEY_PASS }}" | docker sign "${SHA_IMAGE_NAME}"
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Set Dist Version
        run: |
          BUILD_NUMBER="${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
          echo "DIST_VERSION=${DIST_VERSION_PREFIX}-${{ steps.date.outputs.date }}-${BUILD_NUMBER}" >> $GITHUB_ENV
      - name: Create Tag
        uses: actions/github-script@v6
        with:
          script: |
            const {DIST_VERSION} = process.env
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${DIST_VERSION}`,
                sha: context.sha
            })
